import { test, expect } from '@playwright/test'

test('desktop navbar retains authored hover and scroll behavior', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('about/')
  await expect(page.getByRole('heading', { name: 'Built with purpose. Connected by design.' })).toBeVisible()
  await expect(page.locator('.boot-loader')).toHaveCount(0)
  await expect(page.locator('.aegis-about')).toHaveAttribute('data-prepared', 'true', { timeout: 10000 })
  const nav = page.locator('.aegis-nav')
  const products = page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Products', exact: true })
  await products.hover()
  await expect(products.locator('.alt')).toHaveCSS('transform', 'none')
  await page.screenshot({ path: '/tmp/aegis-navbar-desktop.png' })
  await page.mouse.move(700, 300)
  await page.evaluate(() => window.scrollTo({ top: 1100, behavior: 'instant' }))
  await expect(nav).toHaveClass(/stuck.*hide/)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await expect(nav).not.toHaveClass(/hide/)
  await products.click()
  await expect(page).toHaveURL(/\/products$/)
  await expect(products).toHaveAttribute('aria-current', 'page')
})

test('mobile sheet opens from a hidden navbar and closes with keyboard or navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('about/')
  await expect(page.getByRole('heading', { name: 'Built with purpose. Connected by design.' })).toBeVisible()
  await expect(page.locator('.boot-loader')).toHaveCount(0)
  await expect(page.locator('.aegis-about')).toHaveAttribute('data-prepared', 'true', { timeout: 10000 })
  const toggle = page.getByRole('button', { name: 'Toggle navigation menu' })
  const nav = page.locator('.aegis-nav')
  await page.evaluate(() => window.scrollTo({ top: 1000, behavior: 'instant' }))
  await expect(nav).toHaveClass(/hide/)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  const sheet = page.getByRole('navigation', { name: 'Main navigation' })
  await expect(sheet).toBeInViewport()
  await expect(sheet).toHaveCSS('transform', 'none')
  await page.screenshot({ path: '/tmp/aegis-navbar-mobile.png' })
  expect(await page.locator('.main-content').evaluate(el => (el as HTMLElement).inert)).toBe(true)
  await toggle.focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('banner').getByRole('link', { name: 'AEGIS home' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(toggle).toBeFocused()
  expect(await page.locator('.main-content').evaluate(el => (el as HTMLElement).inert)).toBe(false)
  await toggle.click()
  await sheet.getByRole('link', { name: 'Docs', exact: true }).click()
  await expect(page).toHaveURL(/\/docs$/)
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await toggle.click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.locator('.aegis-nav-burger')).toHaveAttribute('aria-expanded', 'false')
  expect(await page.locator('.main-content').evaluate(el => (el as HTMLElement).inert)).toBe(false)
})

test('reduced motion removes navigation transitions', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('about/')
  await expect(page.getByRole('heading', { name: 'Built with purpose. Connected by design.' })).toBeVisible()
  await expect(page.locator('.boot-loader')).toHaveCount(0)
  await expect(page.locator('.aegis-about')).toHaveAttribute('data-prepared', 'true', { timeout: 10000 })
  await expect(page.locator('.aegis-nav')).toHaveCSS('transition-duration', '0s')
  await expect(page.locator('.aegis-nav-link .alt').first()).toHaveCSS('transition-duration', '0s')
})
